# TODO: rsync docker images pri deploy, ne pri buildu image. Image mezitim ulozit v CircleCI workspace.
# TODO: Verifikace, ze to, co se nasazuje, je to, co se zbuildilo (ze to neni z jineho commitu apod.)

version: 2
jobs:
  build_docker_image:
    docker:
      - image: docker:stable
    working_directory: /src
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
          - v3-docker_image
      - run: gunzip /docker_image_cw.tar.gz || true
      - run: docker load -i /docker_image_cw.tar || true
      - run: docker images
      - run: docker build -t cw --pull --cache-from cw .
      - run: docker save -o /docker_image_cw.tar cw
      - run: gzip -k3 /docker_image_cw.tar
      - save_cache:
          key: v3-docker_image-{{ .Branch }}-{{ epoch }}
          paths:
          - /docker_image_cw.tar.gz
      - run: docker images
      - run: &setup_ssh_server_key_fingerprint
          name: setup SSH server key fingerprint
          command: |
            mkdir -p ~/.ssh
            echo '207.154.235.213 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMd2qF3m1mtvgxq45xX8F+po9GLeGFgqXp051IsZZKKi' >> ~/.ssh/known_hosts
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" -o "${CIRCLE_BRANCH}" == "201809_single_dockerfile" ]; then
              set -ex
              apk add openssh rsync
              rsync -vz --progress /docker_image_cw.tar circleci@207.154.235.213:
            fi

  call_deploy_script:
    docker:
      - image: circleci/python:3.6
    steps:
      - run: *setup_ssh_server_key_fingerprint
      - deploy:
          command: |
            ssh circleci@207.154.235.213 sudo /root/pyladies-courseware/deployment/ci_deploy.sh

  call_deploy_demo_script:
    docker:
      - image: circleci/python:3.6
    steps:
      - run: *setup_ssh_server_key_fingerprint
      - deploy:
          command: |
            ssh circleci@207.154.235.213 sudo /root/pyladies-courseware/deployment/ci_deploy_demo.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_docker_image
      #- call_deploy_script:
      #    requires:
      #      - build_docker_image
      #    filters:
      #      branches:
      #        only: master
      - call_deploy_demo_script:
          requires:
            - build_docker_image
          filters:
            branches:
              #only: master
              only: 201809_single_dockerfile
